In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# **Check for GPU**

**CPU vs GPU vs TPU**
The difference between CPU, GPU and TPU is that the CPU handles all the logics, calculations, and input/output of the computer, it is a general-purpose processor. In comparison, GPU is an additional processor to enhance the graphical interface and run high-end tasks. TPUs are powerful custom-built processors to run the project made on a specific framework, i.e. TensorFlow.

**CPU:** Central Processing Unit. Manage all the functions of a computer.

**GPU:** Graphical Processing Unit. Enhance the graphical performance of the computer.

**TPU:** Tensor Processing Unit. Custom build ASIC to accelerate TensorFlow projects.

**What is the CPU?**
CPU stands for Central Processing Unit and considered as the brain of the computer.
It is the primary hardware of the computer that executes the instruction for computer programs. All the basic arithmetic, logic, controlling, and the CPU handles input/output functions of the program.

CPU runs the operating system, continually receiving inputs and providing output to the users.

A CPU contains at least one processor. The processor is an actual chip inside the CPU to perform all the calculations. For a long time, CPUs had only one processor, but now dual-core CPUs (CPU with two processors) are common.

There are also four-processor CPUs that are quad-core CPUs. Some high-end companies also build CPUs with eight processors.

**CPU vs GPU vs TPU:**
Understanding the Difference Between Them
Popular Manufacturers: Intel, AMD, Qualcomm, NVIDIA, IBM, Samsung, Hewlett-Packard, VIA, etc

**What is the GPU?**

While CPU is known as the brain of the computer, and the logical thinking section of the computer, GPU helps in displaying what is going on in the brain by rendering the graphical user interface visually.

GPU stands for Graphical Processing Unit, and it is integrated into each CPU in some form. But some tasks and applications require extensive visualization that available inbuilt GPU can’t handle. Tasks such as computer-aided design, machine learning, video games, live streamings, video editing, and data scientist.

Simple tasks of rendering basic graphics can be done with the GPU built into the CPU. For other high-end jobs, GPU is made.

Moreover, if you want to do extensive graphical tasks, but do not want to invest in physical GPU, you can get GPU servers. GPU servers are servers with GPU that you can remotely use to harness the raw processing power to complex calculations.

CPU vs GPU vs TPU: Understanding the Difference Between Them
Popular GPU Manufacturers: NVIDIA, AMD, Broadcom Limited,

GPU is typically expensive. Best option is to get GPU server on rent, and use the GPU power without buying the GPU server. Get your GPU server now.

**What is TPU?**
Tensor Processing Unit (TPU) is an application-specific integrated circuit, to accelerate the AI calculations and algorithm. Google develops it specifically for neural network machine learning for the TensorFlow software. Google owns TensorFlow software.

Google started using TPU in 2015; then, they made it public in 2018. You can have TPU as a cloud or smaller version of the chip.

TPUs are custom build processing units to work for a specific app framework. That is TensorFlow. An open-source machine learning platform, with state of the art tools, libraries, and community, so the user can quickly build and deploy ML apps.

Cloud TPU allows you to run your machine learning projects on TPU using TF. Designed for powerful performance, and flexibility, Google’s TPU helps researchers and developers to run models with high-level TensorFlow APIs.

The models who used to take weeks to train on GPU or any other hardware can put out in hours with TPU.

TPU is only used for TensorFlow projects by researchers and developers.

CPU vs GPU vs TPU: Understanding the Difference Between Them
Manufacturer: Only Google makes them.

**# CPU vs GPU vs TPU**
CPU	                         GPU	                                  TPU
Several core	           Thousands of Cores	           Matrix based workload
Low latency	             High data throughput	         High latency
Serial processing	       Massive parallel computing	   High data throughput
Limited simultaneous
operations	             Limited multitasking	      Suited for large batch sizes
Large memory capacity	   Low memory	               Complex neural network models


In [ ]:
!nvidia-smi

Wed Aug  2 14:46:49 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(device)

cuda


In [ ]:
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-c77345a6-ad86-f8e0-4e61-18ff843dd665)


# **News Classification Code**

In [ ]:
pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 18.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 29.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 45.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 43.9 MB/s eta 0:00:00


In [ ]:
import pandas as pd
import numpy as np
#!pip install transformers
from transformers import BertTokenizer
import tensorflow as tf
from transformers import TFAutoModel

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/A_Classification/New_Classifi_Dataset.csv')

In [ ]:
df.head()

Text        Category
0  "I don't get paid for this. I'm here just for ...          SPORTS
1  Who's going to hold your hand through yet anot...    FOOD & DRINK
2  I am always looking for vacation destinations ...          TRAVEL
3  Here it is: The full Victoria Beckham editoria...  STYLE & BEAUTY
4  We've been seeing a lot of stars stepping out ...  STYLE & BEAUTY

In [ ]:
df.shape

(42255, 2)

In [ ]:
df['Category'].unique()

array(['SPORTS', 'FOOD & DRINK', 'TRAVEL', 'STYLE & BEAUTY', 'POLITICS',
       'ENTERTAINMENT', 'WELLNESS', 'BUSINESS', 'PARENTING'], dtype=object)

In [ ]:
df.Category.value_counts()

SPORTS            4695
FOOD & DRINK      4695
TRAVEL            4695
STYLE & BEAUTY    4695
POLITICS          4695
ENTERTAINMENT     4695
WELLNESS          4695
BUSINESS          4695
PARENTING         4695
Name: Category, dtype: int64

In [ ]:
seq_len = 512
num_samples = len(df)
Xids = np.zeros((num_samples,seq_len))
Xmask = np.zeros((num_samples,seq_len))
Xids.shape

(42255, 512)

In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

for i,Text in enumerate(df['Text']):
  tokens = tokenizer.encode_plus(Text,max_length=seq_len,truncation=True,
                                 padding='max_length',add_special_tokens=True,
                                 return_tensors='tf')
  Xids[i,:] = tokens['input_ids']
  Xmask[i,:] = tokens['attention_mask']

Downloading:   0%|          | 0.00/213k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [ ]:
Xids

array([[ 101.,  107.,  146., ...,    0.,    0.,    0.],
       [ 101., 2627.,  112., ...,    0.,    0.,    0.],
       [ 101.,  146., 1821., ...,    0.,    0.,    0.],
       ...,
       [ 101., 3949., 1103., ...,    0.,    0.,    0.],
       [ 101., 1135.,  188., ...,    0.,    0.,    0.],
       [ 101., 1249., 1111., ...,    0.,    0.,    0.]])

In [ ]:
Xmask

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.]])

In [ ]:
possible_labels = df.Category.unique()

label_dict = {}
for index, possible_label in enumerate(possible_labels):
    label_dict[possible_label] = index
label_dict

{'SPORTS': 0,
 'FOOD & DRINK': 1,
 'TRAVEL': 2,
 'STYLE & BEAUTY': 3,
 'POLITICS': 4,
 'ENTERTAINMENT': 5,
 'WELLNESS': 6,
 'BUSINESS': 7,
 'PARENTING': 8}

In [ ]:
df['label'] = df.Category.replace(label_dict)

In [ ]:
df.head()

Text        Category  label
0  "I don't get paid for this. I'm here just for ...          SPORTS      0
1  Who's going to hold your hand through yet anot...    FOOD & DRINK      1
2  I am always looking for vacation destinations ...          TRAVEL      2
3  Here it is: The full Victoria Beckham editoria...  STYLE & BEAUTY      3
4  We've been seeing a lot of stars stepping out ...  STYLE & BEAUTY      3

In [ ]:
arr = df['label'].values
arr

array([0, 1, 2, ..., 0, 0, 3])

In [ ]:
labels = np.zeros((num_samples,arr.max()+1))
labels.shape

(42255, 9)

In [ ]:
labels[np.arange(num_samples),arr] = 1

In [ ]:
labels

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices((Xids,Xmask,labels))
dataset.take(1)

<TakeDataset element_spec=(TensorSpec(shape=(512,), dtype=tf.float64, name=None), TensorSpec(shape=(512,), dtype=tf.float64, name=None), TensorSpec(shape=(9,), dtype=tf.float64, name=None))>

In [ ]:
Xids[0,:].shape

(512,)

In [ ]:
labels[0,:].shape

(9,)

In [ ]:
def map_func(input_ids,masks,labels):
  return {'input_ids':input_ids,'attention_mask':masks},labels

In [ ]:
dataset = dataset.map(map_func)

In [ ]:
dataset

<MapDataset element_spec=({'input_ids': TensorSpec(shape=(512,), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(512,), dtype=tf.float64, name=None)}, TensorSpec(shape=(9,), dtype=tf.float64, name=None))>

In [ ]:
dataset.take(1)

<TakeDataset element_spec=({'input_ids': TensorSpec(shape=(512,), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(512,), dtype=tf.float64, name=None)}, TensorSpec(shape=(9,), dtype=tf.float64, name=None))>

In [ ]:
batch_size = 12

dataset = dataset.shuffle(10000).batch(batch_size,drop_remainder=True)

dataset.take(1)

<TakeDataset element_spec=({'input_ids': TensorSpec(shape=(12, 512), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(12, 512), dtype=tf.float64, name=None)}, TensorSpec(shape=(12, 9), dtype=tf.float64, name=None))>

In [ ]:
split = 0.9

size = int((num_samples/batch_size))

In [ ]:
trains_ds = dataset.take(size)
val_ds = dataset.skip(size)

del dataset

In [ ]:
#from transformers import TFAutoModel
bert = TFAutoModel.from_pretrained('bert-base-uncased')

bert.summary()

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/536M [00:00<?, ?B/s]

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


Model: "tf_bert_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  109482240 
                                                                 
Total params: 109,482,240
Trainable params: 109,482,240
Non-trainable params: 0
_________________________________________________________________


In [ ]:
input_ids = tf.keras.layers.Input(shape=(seq_len,),name='input_ids',dtype='int32')
mask = tf.keras.layers.Input(shape=(seq_len,),name='attention_mask',dtype='int32')

embeddings = bert.bert(input_ids,attention_mask=mask)[1]

x = tf.keras.layers.Dense(1024,activation='relu')(embeddings)
y = tf.keras.layers.Dense(arr.max()+1,activation='softmax',name='outputs')(x)

In [ ]:
model = tf.keras.Model(inputs=[input_ids,mask],outputs=y)


model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, 512)]        0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 512)]        0           []                               
                                                                                                  
 bert (TFBertMainLayer)         TFBaseModelOutputWi  109482240   ['input_ids[0][0]',              
                                thPoolingAndCrossAt               'attention_mask[0][0]']         
                                tentions(last_hidde                                               
                                n_state=(None, 512,                                           

In [ ]:
optimizer = tf.keras.optimizers.Adam(lr=1e-5,decay=1e-6)
loss = tf.keras.losses.CategoricalCrossentropy()
acc = tf.keras.metrics.CategoricalAccuracy('accuracy')

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
from torch import cuda
device = 'cuda' if cuda.is_available() else 'cpu'

In [ ]:
model.compile(optimizer=optimizer,loss=loss,metrics=[acc])

In [ ]:
history = model.fit(
    trains_ds,
    validation_data = val_ds,
    epochs = 7
)

Epoch 1/7
3521/3521 [==============================] - 2993s 846ms/step - loss: 1.8468 - accuracy: 0.3190
Epoch 2/7
3521/3521 [==============================] - 2978s 846ms/step - loss: 1.3623 - accuracy: 0.5327
Epoch 3/7
3521/3521 [==============================] - 2979s 846ms/step - loss: 1.0739 - accuracy: 0.6388
Epoch 4/7
3521/3521 [==============================] - 2979s 846ms/step - loss: 0.8580 - accuracy: 0.7145
Epoch 5/7
3521/3521 [==============================] - 2979s 846ms/step - loss: 0.6755 - accuracy: 0.7767
Epoch 6/7
3521/3521 [==============================] - 2978s 846ms/step - loss: 0.5136 - accuracy: 0.8327
Epoch 7/7
3521/3521 [==============================] - 2978s 846ms/step - loss: 0.3874 - accuracy: 0.8729


In [ ]:
#Saving a mode
model.save("/content/drive/MyDrive/Colab Notebooks/A_Classification/1f_classification_model.h5")
print("Saved model to drive")

Saved model to drive


# **Save Model Code**

In [ ]:
# #Know the version of h5py library
# import h5py
# print(h5py.__version__)

In [ ]:
#Saving a mode
model.save("/content/drive/MyDrive/Colab Notebooks/A_Classification/2news_classification_model.h5")
print("Saved model to drive")

NameError: ignored

In [ ]:
#Loading a model and train
from keras.models import load_model

model = load_model('/content/drive/MyDrive/Colab Notebooks/A_Classification/news_classification_model.h5')

model.fit(trains_ds,validation_data = val_ds,epochs = 1)

4166/4166 [==============================] - 3530s 845ms/step - loss: 1.1230 - accuracy: 0.6369


In [ ]:
#Saving a mode
model.save("/content/drive/MyDrive/Colab Notebooks/A_Classification/news_classification_model4epoch.h5")
print("Saved model to disk")

Saved model to disk


# **Train Model Details**

In [ ]:
# Classification Model
#Relu + Softmax
#1-3 epoch model_name=news_classification_model.h5
#path /content/drive/MyDrive/Colab Notebooks/A_Classification/news_classification_model.h5
#from IPython.display import Image
Image('/content/drive/MyDrive/Colab Notebooks/A_Classification/1_3epoch_relu_softmax.jpg')

In [ ]:
#3-4 epoch model_name=news_classification_model4epoch.h5
#Relu + Softmax
#path /content/drive/MyDrive/Colab Notebooks/A_Classification/news_classification_model4epoch.h5
Image('/content/drive/MyDrive/Colab Notebooks/A_Classification/3-4_epoch_relu_softmax.jpg')

# **For Text prediction**

In [ ]:
model = tf.keras.models.load_model('/content/drive/MyDrive/Colab Notebooks/A_Classification/news_classification_model4epoch.h5')

model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, 512)]        0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 512)]        0           []                               
                                                                                                  
 bert (TFBertMainLayer)         TFBaseModelOutputWi  109482240   ['input_ids[0][0]',              
                                thPoolingAndCrossAt               'attention_mask[0][0]']         
                                tentions(last_hidde                                               
                                n_state=(None, 512,                                           

In [ ]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-cased')

def prep_data(text):
  tokens = tokenizer.encode_plus(text,max_length=512,
                                 truncation=True,padding='max_length',
                                 add_special_tokens=True,return_token_type_id=False,
                                 return_tensors='tf')
  return{
      'input_ids':tf.cast(tokens['input_ids'],tf.float64),
      'attention_mask':tf.cast(tokens['attention_mask'],tf.float64)
  }

In [ ]:
test = prep_data("We know there s that pesky clause in the Constitution and all, but doesn t it seem like today would have been more appropriate")

Keyword arguments {'return_token_type_id': False} not recognized.


In [ ]:
probs = model.predict(test)

probs[0]

array([2.2325137e-04, 8.1910816e-04, 2.9960729e-04, 2.9400998e-04,
       4.4999763e-04, 3.2372880e-04, 6.8935249e-03, 1.0253862e-02,
       4.9535222e-02, 9.3090773e-01], dtype=float32)

In [ ]:
import numpy as np

np.argmax(probs[0])

9

In [ ]:
# {'SPORTS': 0,
#  'BUSINESS': 1,
#  'TRAVEL': 2,
#  'TECHNOLOGY': 3,
#  'STYLE & BEAUTY': 4,
#  'FOOD & DRINK': 5,
#  'POLITICS': 6,
#  'ENTERTAINMENT': 7,
#  'PARENTING': 8,
#  'WELLNESS': 9}